name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SECRET_KEY: django-secret-key-for-test
  # DEBUG should be empty for false value
  DEBUG: ''
  PROJECT_ROOT: /home/runner/work/NeedBuy/NeedBuy/apps

jobs:

  services:
    postgres:
      image: postgres:latest
      env:
        POSTGRES_DB: postgres_db
        POSTGRES_PASSWORD: postgres_password
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres_user
      ports:
        - 5432:5432
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Query database
        run: psql -h postgres -d postgres_db -U postgres_user -c 'SELECT 1;'
        env:
          PGPASSWORD: postgres_password
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r NeedBuy/requirements.txt
      - name: Run migrations
        run: |
          python NeedBuy/manage.py migrate
      - name: Run Tests
        run: |
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          python NeedBuy/manage.py test
