# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]

env:
  SECRET_KEY: django-secret-key-for-test
  # DEBUG should be empty for false value
  DEBUG: ''
  PROJECT_ROOT: /home/runner/work/NeedBuy/NeedBuy/apps

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r NeedBuy/requirements.txt
    - name: Run migrations
      run: python NeedBuy/manage.py migrate
    - name: Run tests
      run: python NeedBuy/manage.py test
